config/routes.rb
Rails.application.routes.draw do
  root "stations#index"
  devise_for :users

  resources :stations, only: [:index, :show, :new, :create] do
    resources :reviews, except: [:show, :index, :destroy]
    resources :station_images, only: [:create]
  end

  resources :reviews, only: [] do
    resources :votes, only: [:destroy]
    get '/up-vote', to: 'votes#up_vote', as: :up_vote
    get '/down-vote', to: 'votes#down_vote', as: :down_vote
  end


  resources :reviews, only: [:destroy]

  namespace :admin do
    resources :stations
    resources :users, only: [:index, :destroy, :update]
  end
end

app/models/station.rb
class Station < ActiveRecord::Base
  has_many :lines, through: :connection
  has_many :connections
  has_many :reviews
  has_many :station_images
  validates :name, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  accepts_nested_attributes_for :connections

  def self.get_lat_lng(address)
    Geokit::Geocoders::GoogleGeocoder.geocode "#{address}"
  end

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < ApplicationController
  def index
    @stations = Station.all
  end

  def show
    @station = Station.find(params[:id])
  end

  def new
    @station = Station.new
    @lines = Line.all
    if current_user.nil? || current_user.role != "admin"
      flash[:notice] = "Only admins can create stations"
      redirect_to stations_path
    end
  end

  def create
    @station = Station.new(station_params)
    location_object = Station.get_lat_lng(@station.address)
    @station.latitude = location_object.lat
    @station.longitude = location_object.lng
    if current_user.nil? || current_user.role != "admin"
      flash[:notice] = "Only admins can create stations"
      redirect_to stations_path
    elsif @station.save
      @connection = Connection.new(
        station_id: @station.id,
        line_id: params["line_id"].to_i
      )
      @connection.save
      flash[:notice] = "Station created."
      redirect_to admin_station_path(@station)
    else
      @errors = @station.errors.full_messages
      @lines = Line.all
      render new_admin_station_path
    end
  end

  def edit
    if current_user.nil? || current_user.role != "admin"
      flash[:notice] = "Only admins can edit stations"
      redirect_to stations_path
    else
      @station = Station.find(params[:id])
    end
  end

  def update
    @station = Station.find(params[:id])
    if current_user.nil? || current_user.role != "admin"
      flash[:notice] = "Only admins can edit stations"
      redirect_to stations_path
    elsif @station.update(station_params)
      flash[:notice] = "Station edited."
      redirect_to @station
    else
      @errors = @station.errors.full_messages
      render "edit"
    end
  end

  def destroy
    @station = Station.find(params[:id])
    if current_user.nil? || current_user.role != "admin"
      flash[:notice] = "Only admins can delete stations"
      redirect_to stations_path
    else
      @station.destroy
      flash[:notice] = "Station deleted"
      redirect_to stations_path
    end
  end

  private

  def station_params
    params.require(:station).permit(:name, :address, :line)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index
    if params[:search]
      @stations = Station.search(params[:search])
      if @stations.empty?
        @error = 
        "Your search returned no results. Try using different keywords."
      end
    else
      @stations = Station.all
    end
    @lines = Line.all
  end

  def show
    @station = Station.find(params[:id])
    @user = current_user

    @reviews = @station.reviews.page params[:page]
    @review = Review.new

    @votes = @review.votes

    @image = StationImage.new
  end

end

app/views/stations/_votes.html.erb
 
<div class="ui vertical buttons page grid item">
      <a class="ui pointing below label centered"><h4>
            THIS<br>
            REVIEW<br>
           WAS</h4></a>
        <%= button_to "GOOD", review_up_vote_path(review), class: 'ui inverted green toggle button', style: 'padding: 20px;' %>
        <%= button_to "BAD", review_up_vote_path(review), class: 'ui inverted red toggle button', style: 'padding: 20px;' %>
        <% vote = Vote.where(user_id: @user.id, review_id: review.id)[0] if @user %>
  <% if vote %>
    <%= button_to "Delete Vote", review_vote_path(review, vote.id),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this vote?" }%>
  <% end %>
</div>

app/views/stations/edit.html.erb
<%= form_for @station do |f| %>
  <%if @station.errors.any? %>
    <ul>
      <% @station.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, :value => @station.name %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address, :value => @station.address %>
  </div>

  <%= f.submit 'Submit' %>
<% end %>

app/views/stations/index.html.erb
<%= @error %>


<div class="ui four item menu centered" style = "box-shadow: none;">
  <a class="red item">
      <div class="ui red circular label"></div>
  </a>
  <a class="green item">
      <div class="ui green circular label"></div>
  </a>
  <a class="blue item">
      <div class="ui blue circular label"></div>
  </a>
  <a class="orange item">
      <div class="ui orange circular label"></div>
  </a>
</div>
<div>
 <div class="ui four column grid centered">
  <% @lines.each do |line| %>
   <div class="column">
    <% line.stations.each do |station| %>
       <div class="ui segment centered column grid " style="background: none; box-shadow: none;" >
            <div class ="column"></div>
            <a class="ui <%= line.name.downcase%> circular label">
</a>
<!--
        <div class="ui fluid row" id="circle" style="width: 4px;height: 4px;background: black;-moz-border-radius: 50px;-webkit-border-radius: 50px;border-radius: 50px;">
</div>
-->
         <p class="column"><%= link_to station.name, station_path(station) %></p>
      </div>
    <% end %>
  </div>
  <% end %>
<div>

app/views/stations/show.html.erb
<!-- <img src="http://maps.googleapis.com/maps/api/staticmap?center=<%= @station.latitude + "," + @station.longitude %>&zoom=16&format=png&sensor=false&size=640x480&maptype=roadmap&style=feature:administrative|visibility:off&style=feature:poi|visibility:off&style=feature:road.highway|element:labels|visibility:off&style=feature:water|element:labels|visibility:off&style=feature:road.arterial|element:labels|visibility:off|lightness:85&style=feature:road.local|element:labels|visibility:off&style=feature:landscape|element:geometry.fill|color:0xffffff&style=feature:road.highway|element:geometry.fill|hue:0xff7700|weight:3.8|lightness:100|gamma:0.2&style=feature:road.arterial|element:geometry.fill|color:0x7d8080|lightness:77&style=feature:road.local|element:geometry.fill|color:0x808080|lightness:97|gamma:0.55&style=feature:water|gamma:0.28|lightness:82&style=feature:transit.station|visibility:off&style=feature:road.highway|element:geometry&style=feature:transit.line|visibility:off&style=feature:water"> -->
<div class="overlay" onClick="style.pointerEvents='none'"></div>
<iframe width="100%" height="150" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBmaUUgreBb8VainWXdk6ugZ3eroEoEeYw&q=<%= @station.latitude + "," + @station.longitude %>&zoom=18&maptype=roadmap"></iframe>
<div class="ui card header description" style="
    position: absolute;
    left: 0;
    top: 116px;
    padding: .5% 0% .5% 2%;
    box-shadow: inset 5px 5px 4px rgba(255, 255, 255, 0), inset -5px -5px 4px rgba(247, 247, 247, 0.06);
    /* z-index: -1; */
    background: rgb(255, 255, 255);
    color: rgb(27, 28, 29);
    /* text-shadow: 0px 0px 0px rgba(160, 149, 149, 0.25), 3px 1px 1px rgba(255, 255, 255, 0.24), 0px 0px 0px rgba(5, 4, 4, 0.22), 0px 0px 0px rgba(0, 0, 0, 0.05); */
    font-size: large;
    border-radius: 2px;

    border: solid 1px rgb(209, 209, 209);"
    >
<%= @station.name %>
<%= @station.address %>
</div>

<div class="ui grid">
  <% @station.station_images.each do |station_image| %>
      <%= image_tag(station_image.image.url, alt: station_image.description, class: "four wide column" )%>
      <%= station_image.description %>
  <% end %>
</div>

<%= render partial: "reviews/show", locals: { station: @station } %>
<div class="ui card" style="width: 80%;
margin: 5% 10% 0% 10%;">
<div class="ui card" style="display: inline-block;
margin: 3%;
width: 94%;">
  <div class="ui label blue">Write a review for <%= @station.name %>!</div>
  <%= form_for [@station, @review], html: {class: "ui fluid form", style: "width: 96%; display: inline-block; padding: 0%; margin: 2%;"} do |f| %>
    <%= f.label :description %>
    <%= f.text_area :description, style: "margin-bottom: 1%;", placeholder: "Enter a description"%>
    <%= f.select(:rating, %w[1 2 3 4], {prompt: 'Rating'}, html: {class: "ui selection dropdown"}) %>
    <%= f.submit "Submit", class: "ui button black", style: "margin-top: 1%;" %>
  <% end %>
</div>

<div class="ui card" style="margin: 3%;
width: 94%;">
  <div class="ui label blue">
  Upload a photo of <%= @station.name %>!
  </div>
  <%= form_for [@station, @image], html: {class: "ui fluid form", style: "width: 100%; padding: 3%; bottom: 0; top: 0; left: 0;"} do |f| %>
    <div class="field">
    <%= f.label :image, "Image" %>
    <%= f.file_field :image %>
    </div>
    <div class="field">
    <%= f.label :description, "Image Description" %>
    <%= f.text_field :description %>
    </div>
    <%= f.hidden_field :station_id, value: @station.id %>
    <%= f.submit "Add photo", class: "ui submit button black" %>
  <% end %>
  </div>
</div>
</div>

<%= link_to "Delete", station_path(@station), method: :delete, data: { confirm: 'Are you sure?' } %>