config/routes.rb
Rails.application.routes.draw do
  root "stations#index"
  devise_for :users

  resources :stations, only: [:index, :show, :new, :create] do
    resources :reviews, except: [:show, :index, :destroy]
    resources :station_images, only: [:create]
  end

  resources :reviews, only: [] do
    resources :votes, only: [:destroy]
    get '/up-vote', to: 'votes#up_vote', as: :up_vote
    get '/down-vote', to: 'votes#down_vote', as: :down_vote
  end


  resources :reviews, only: [:destroy]

  namespace :admin do
    resources :stations
    resources :users, only: [:index, :destroy, :update]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate

  def update
    @review = Review.find(params[:id])
    if @review.update_attributes(params[:review].permit(:description, :rating))
      flash[:notice] = "Review edited"
      redirect_to parent
    else
      @station = parent
      @errors = @review.errors.full_messages
      render "reviews/edit"
    end
  end

  def new
    @review = parent.reviews.new(review_params)
  end

  def create
    @review = parent.reviews.new(review_params)
    @review.user_id = current_user.id

    if @review.save
      flash[:notice] = "Review created"
      redirect_to parent
    else
      @image = StationImage.new
      render "stations/show"
    end
  end

  def edit
    @station = parent
    @review = Review.find(params[:id])
    authenticate_review(@review)
  end

  def destroy
    @review = Review.find(params[:id])
    return unless authenticate_review(@review)
    @station = @review.station
    @review.destroy
    redirect_to station_path(@station)
  end

  private

  def parent
    @station ||= Station.find(params[:station_id])
  end

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/views/reviews/_show.html.erb
<% if @review.errors.any? %>
  <% @review.errors.full_messages.each do |error| %>
    <%= error %>
  <% end %>
<% end %>
<% if !@reviews.nil? %>
<div class ="ui comments two horizontal items">
<ul>
  <% @reviews.each do |review| %>
  <div class = "ui segment comment item">
   <% if @user && (@user == review.user || @user.role == "admin") %>
      <%= link_to "Edit this review", edit_station_review_path(@station, review) %>
      <%= button_to "Delete",
      review_path(review),
      method: :delete,
      action: :destroy,
      data: { confirm: "Are you sure you want to delete this review?" }%>
      </div>
    <% else %>
        <%= render partial: 'stations/votes', locals: { station: @station, review: review } %>
    <div><%= review.description %></div>
    <%= review.rating %>
    <% end %>
  </div>
  <% end %>
</ul>
</div>
<%= paginate @reviews %>

<% end %>

app/views/reviews/edit.html.erb
<% if @review.errors.any? %>
  <div class="errors">
    <% @review.errors.full_messages.each do |error| %>
      <%= error %>!
    <% end %>
  </div>
<% end %>

<%= form_for [@station, @review] do |f| %>
<div>
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>


<div>
  <%= f.label :rating %>
  <%= f.select(:rating, %w[1 2 3 4], {prompt: 'Rating'}) %>
</div>

<div>
  <%= f.submit "Update" %>
</div>

<% end %>