config/routes.rb
Rails.application.routes.draw do
  root "stations#index"
  devise_for :users

  resources :stations, only: [:index, :show, :new, :create] do
    resources :reviews, except: [:show, :index, :destroy]
    resources :station_images, only: [:create]
  end

  resources :reviews, only: [] do
    resources :votes, only: [:destroy]
    get '/up-vote', to: 'votes#up_vote', as: :up_vote
    get '/down-vote', to: 'votes#down_vote', as: :down_vote
  end


  resources :reviews, only: [:destroy]

  namespace :admin do
    resources :stations
    resources :users, only: [:index, :destroy, :update]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>sTaTion!</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
</head>
<body>

  <nav class="ui menu">
      <div class="item"><h1><a href="/">sTaTion!</a></h1>
        <% if current_user %>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "ui gray button"%>
          <%= link_to 'User Settings', edit_user_registration_path, method: :get, class: "ui gray button" %>
        <% else %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "ui gray button" %>
          <%= link_to 'Sign In', new_user_session_path, class: "ui gray button" %>
        <% end %>
      </div>
      <div class="right menu">
      <div class="item">
        <div class="ui form">
          <%= form_tag(stations_path, method: "get") do %>
          <div class="field">
            <%= text_field_tag(:search, params[:search], placeholder: "Search Stations") %>
          </div>
          <%= submit_tag "Search", class: "ui gray button" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="ui message red">
      <%= value %>
    </div>
  <%- end -%>
  <div>
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>